DROP TABLE VIK_DEPARTEMENT CASCADE CONSTRAINTS;
DROP TABLE VIK_TYPE_CLIENT CASCADE CONSTRAINTS;
DROP TABLE VIK_TARIF CASCADE CONSTRAINTS;
DROP TABLE VIK_COMMUNE CASCADE CONSTRAINTS;
DROP TABLE VIK_LIGNE CASCADE CONSTRAINTS;
DROP TABLE VIK_CLIENT CASCADE CONSTRAINTS;
DROP TABLE VIK_REDUCTION CASCADE CONSTRAINTS;
DROP TABLE vik_reservation CASCADE CONSTRAINTS;
DROP TABLE VIK_ETAPE CASCADE CONSTRAINTS;
DROP TABLE VIK_NOEUD CASCADE CONSTRAINTS;

CREATE TABLE VIK_DEPARTEMENT
( 
    DEP_NUM CHAR(3)  NOT NULL,
    DEP_NOM VARCHAR2(32)  NULL,
	CONSTRAINT PK_VIK_DEPARTEMENT PRIMARY KEY (DEP_NUM)  
);

CREATE TABLE VIK_TYPE_CLIENT
( 
    TYP_NUM NUMBER(10)  NOT NULL,
    TYP_NOM VARCHAR2(32)  NULL,
    TYP_PT_LIMITE NUMBER( 6)  NULL,
    TYP_REDUC NUMBER(2)  NULL,
	CONSTRAINT PK_VIK_TYPE_CLIENT PRIMARY KEY (TYP_NUM)  
);

CREATE TABLE VIK_TARIF
( 
    TAR_NUM_TRANCHE NUMBER(2)  NOT NULL,
    TAR_MIN_DIST NUMBER(4,1)  NULL,
    TAR_MAX_DIST NUMBER(4,1)  NULL,
    TAR_PRIX NUMBER(4)  NULL,
	CONSTRAINT PK_VIK_TARIF PRIMARY KEY (TAR_NUM_TRANCHE)  
);

CREATE TABLE VIK_COMMUNE
( 
    COM_CODE_INSEE CHAR(5)  NOT NULL,
    DEP_NUM CHAR(3)  NOT NULL,
    COM_NOM VARCHAR2(64)  NULL,
    COM_POP NUMBER(6)  NULL,
	CONSTRAINT PK_VIK_COMMUNE PRIMARY KEY (COM_CODE_INSEE)  
);

CREATE  INDEX I_FK_VIK_COMMUNE_VIK_DEPARTEME
     ON VIK_COMMUNE (DEP_NUM ASC)
;

CREATE TABLE VIK_LIGNE
( 
    LIG_NUM CHAR(3)  NOT NULL,
    COM_CODE_INSEE_DEBU CHAR(5)  NOT NULL,
    COM_CODE_INSEE_TERM CHAR(5)  NOT NULL,
	CONSTRAINT PK_VIK_LIGNE PRIMARY KEY (LIG_NUM)  
);

CREATE  INDEX I_FK_VIK_LIGNE_VIK_COMMUNE
     ON VIK_LIGNE (COM_CODE_INSEE_DEBU ASC);

CREATE  INDEX I_FK_VIK_LIGNE_VIK_COMMUNE2
     ON VIK_LIGNE (COM_CODE_INSEE_TERM ASC);

CREATE TABLE VIK_CLIENT
( 
    CLI_NUM NUMBER(3)  NOT NULL,
    TYP_NUM NUMBER(10)  NULL,
    DEP_NUM CHAR(3)  NULL,
    CLI_NOM VARCHAR2(64)  NULL,
    CLI_PRENOM VARCHAR2(64)  NULL,
    CLI_VILLE VARCHAR2(64)  NULL,
    CLI_TELEPHONE VARCHAR2( 16)  NULL,
    CLI_COURRIEL VARCHAR2(32)  NULL,
    CLI_MDP VARCHAR2(255) NULL,
    CLI_NB_POINTS_EC NUMBER(4)  NULL,
    CLI_NB_POINTS_TOT NUMBER(6)  NULL,
    CLI_DATE_CONNEC DATE  NULL,
	CONSTRAINT PK_VIK_CLIENT PRIMARY KEY (CLI_NUM)  
);

CREATE  INDEX I_FK_VIK_CLIENT_VIK_TYPE_CLIEN
     ON VIK_CLIENT (TYP_NUM ASC);

CREATE  INDEX I_FK_VIK_CLIENT_VIK_DEPARTEMEN
     ON VIK_CLIENT (DEP_NUM ASC);

CREATE TABLE VIK_REDUCTION
( 
    RED_NB_POINTS NUMBER(4)  NOT NULL,
    RED_VALEUR NUMBER(2)  NULL,
	CONSTRAINT PK_VIK_REDUCTION PRIMARY KEY ( RED_NB_POINTS)  
);

CREATE TABLE vik_reservation
( 
    CLI_NUM NUMBER(3)  NOT NULL,
    RES_NUM NUMBER(4)  NOT NULL,
    TAR_NUM_TRANCHE NUMBER(2)  NOT NULL,
    RES_DATE DATE  NULL,
    RES_NB_POINTS NUMBER(3)  NULL,
    RES_PRIX_TOT NUMBER(5)  NULL,
	CONSTRAINT PK_vik_reservation PRIMARY KEY (CLI_NUM, RES_NUM)  
);

CREATE  INDEX I_FK_vik_reservation_VIK_TARIF
     ON vik_reservation (TAR_NUM_TRANCHE ASC);
	 
CREATE  INDEX I_FK_vik_reservation_VIK_CLIEN
     ON vik_reservation (CLI_NUM ASC);

CREATE TABLE VIK_ETAPE
( 
    LIG_NUM CHAR(3)  NOT NULL,
    CLI_NUM NUMBER(3)  NOT NULL,
    RES_NUM NUMBER(4)  NOT NULL,
    COM_CODE_INSEE_DEPART CHAR(5)  NOT NULL,
    COM_CODE_INSEE_ARRIVEE CHAR(5)  NOT NULL,
    ETA_DISTANCE NUMBER(4,1)  NULL,
    ETA_HEURE DATE  NULL,
	CONSTRAINT PK_VIK_ETAPE PRIMARY KEY (CLI_NUM, RES_NUM, LIG_NUM, COM_CODE_INSEE_DEPART, COM_CODE_INSEE_ARRIVEE)  
);

CREATE  INDEX I_FK_VIK_ETAPE_VIK_LIGNE
     ON VIK_ETAPE (LIG_NUM ASC);

CREATE  INDEX I_FK_VIK_ETAPE_vik_reservation
     ON VIK_ETAPE (CLI_NUM ASC, RES_NUM ASC);

CREATE  INDEX I_FK_VIK_ETAPE_VIK_COMMUNE
     ON VIK_ETAPE (COM_CODE_INSEE_ARRIVEE ASC);

CREATE  INDEX I_FK_VIK_ETAPE_VIK_COMMUNE1
     ON VIK_ETAPE (COM_CODE_INSEE_DEPART ASC);

CREATE TABLE VIK_NOEUD
( 
    LIG_NUM CHAR(3)  NOT NULL,
    COM_CODE_INSEE_ARRET CHAR(5)  NOT NULL,
    COM_CODE_INSEE_SUIVANT CHAR(5)  NOT NULL,
    NOE_HEURE_PASSAGE DATE  NOT NULL,
    NOE_DISTANCE_PROCHAIN NUMBER(5,1)  NULL,
    NOE_DUREE_PROCHAIN NUMBER(4)  NULL,
	CONSTRAINT PK_VIK_NOEUD PRIMARY KEY (LIG_NUM, COM_CODE_INSEE_ARRET, COM_CODE_INSEE_SUIVANT, NOE_HEURE_PASSAGE)  
);

CREATE  INDEX I_FK_VIK_NOEUD_VIK_LIGNE
     ON VIK_NOEUD (LIG_NUM ASC);

CREATE  INDEX I_FK_VIK_NOEUD_VIK_COMMUNE
     ON VIK_NOEUD (COM_CODE_INSEE_ARRET ASC);

CREATE  INDEX I_FK_VIK_NOEUD_VIK_COMMUNE1
     ON VIK_NOEUD ( COM_CODE_INSEE_SUIVANT ASC);

ALTER TABLE VIK_COMMUNE ADD ( 
     CONSTRAINT FK_VIK_COMMUNE_VIK_DEPARTEMENT
          FOREIGN KEY (DEP_NUM)
               REFERENCES VIK_DEPARTEMENT (DEP_NUM));

ALTER TABLE VIK_LIGNE ADD ( 
     CONSTRAINT FK_VIK_LIGNE_VIK_COMMUNE
          FOREIGN KEY (COM_CODE_INSEE_DEBU)
               REFERENCES VIK_COMMUNE (COM_CODE_INSEE));

ALTER TABLE VIK_LIGNE ADD ( 
     CONSTRAINT FK_VIK_LIGNE_VIK_COMMUNE2
          FOREIGN KEY (COM_CODE_INSEE_TERM)
               REFERENCES VIK_COMMUNE (COM_CODE_INSEE));

ALTER TABLE VIK_CLIENT ADD ( 
     CONSTRAINT FK_VIK_CLIENT_VIK_TYPE_CLIENT
          FOREIGN KEY (TYP_NUM)
               REFERENCES VIK_TYPE_CLIENT (TYP_NUM));

ALTER TABLE VIK_CLIENT ADD ( 
     CONSTRAINT FK_VIK_CLIENT_VIK_DEPARTEMENT
          FOREIGN KEY (DEP_NUM)
               REFERENCES VIK_DEPARTEMENT (DEP_NUM));

ALTER TABLE vik_reservation ADD ( 
     CONSTRAINT FK_vik_reservation_VIK_TARIF
          FOREIGN KEY (TAR_NUM_TRANCHE)
               REFERENCES VIK_TARIF (TAR_NUM_TRANCHE));

ALTER TABLE vik_reservation ADD ( 
     CONSTRAINT FK_vik_reservation_VIK_CLIENT
          FOREIGN KEY ( CLI_NUM)
               REFERENCES VIK_CLIENT (CLI_NUM));

ALTER TABLE VIK_ETAPE ADD ( 
     CONSTRAINT FK_VIK_ETAPE_VIK_LIGNE
          FOREIGN KEY (LIG_NUM)
               REFERENCES VIK_LIGNE (LIG_NUM));

ALTER TABLE VIK_ETAPE ADD ( 
     CONSTRAINT FK_VIK_ETAPE_vik_reservation
          FOREIGN KEY ( CLI_NUM, RES_NUM)
               REFERENCES vik_reservation (CLI_NUM, RES_NUM));

ALTER TABLE VIK_ETAPE ADD ( 
     CONSTRAINT FK_VIK_ETAPE_VIK_COMMUNE
          FOREIGN KEY (COM_CODE_INSEE_ARRIVEE)
               REFERENCES VIK_COMMUNE (COM_CODE_INSEE));

ALTER TABLE VIK_ETAPE ADD ( 
     CONSTRAINT FK_VIK_ETAPE_VIK_COMMUNE1
          FOREIGN KEY (COM_CODE_INSEE_DEPART)
               REFERENCES VIK_COMMUNE (COM_CODE_INSEE));

ALTER TABLE VIK_NOEUD ADD ( 
     CONSTRAINT FK_VIK_NOEUD_VIK_LIGNE
          FOREIGN KEY (LIG_NUM)
               REFERENCES VIK_LIGNE (LIG_NUM));

ALTER TABLE VIK_NOEUD ADD ( 
     CONSTRAINT FK_VIK_NOEUD_VIK_COMMUNE
          FOREIGN KEY (COM_CODE_INSEE_ARRET)
               REFERENCES VIK_COMMUNE (COM_CODE_INSEE));

ALTER TABLE VIK_NOEUD ADD ( 
     CONSTRAINT FK_VIK_NOEUD_VIK_COMMUNE1
          FOREIGN KEY (COM_CODE_INSEE_SUIVANT)
               REFERENCES VIK_COMMUNE (COM_CODE_INSEE));
